stages:
  - analyze

analyze:unit:
  stage: analyze
  image:
    name: node:18-alpine3.16
  cache:
    key: '${CI_JOB_NAME}'
    paths:
      - .pnpm-store
  before_script:
    - npm install -g pnpm
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install --no-frozen-lockfile
    - pnpm coverage
  allow_failure: true
  interruptible: true
  artifacts:
    name: "test-cov"
    expire_in: 3 hrs
    paths:
      - /coverage
  only:
    - main
  tags:
    - gits-docker

# stage sonarqube
analyze:sonar:
  stage: analyze
  image:
    name: sonarsource/sonar-scanner-cli:4.8.0
    entrypoint: [ '' ]
  
  needs: ["analyze:unit"]
  cache:
    key: '${CI_JOB_NAME}'
    paths:
      - .sonar/cache
  script:
    - sonar-scanner -Dsonar.host.url=https://sonar.gits.id -Dsonar.login=$SONAR_USER -Dsonar.password=$SONAR_PASSWORD
  interruptible: true
  allow_failure: true
  dependencies:
    - analyze:unit
  only:
    - main
  tags:
    - gits-docker
